### ISSUE TITLE
附加功能

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/db-in-rmd#1]
以 PostgreSQL 为例，自定义数据库名称，用户名，密码等

```
[PostgreSQL]
Driver              = PostgreSQL Unicode
Database            = xiangyun
Servername          = 192.168.99.101
UserName            = xiangyun
Password            = password
Port                = 8080
```

创建数据库登陆用户 xiangyun 会自动创建一个名叫 xiangyun 的数据库

```
   psql:
     image: postgres
     environment:
       #- POSTGRES_PASSWORD=password
       - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
       - POSTGRES_USER=xiangyun
     ports:
       - "8080:5432"
     volumes:
       - ${PWD}/data:/var/lib/postgresql/testdata
       - ${PWD}/pwd:/run/secrets/
```

密码和数据库文件另存
